### ISSUE TITLE
Need help tracing symbolic link error in controller.py

### ISSUE THREAD

**Issue by Daenks** [Netflix/sketchy#16]
>ERROR in controller [/home/dstone/sketchy/sketchy/controllers/controller.py:210]:
>[Errno 40] Too many levels of symbolic links
>--------------------------------------------------------------------------------
>127.0.0.1 - - [19/Mar/2015 12:23:03] "GET /eager?url=http://google.com&type=sketch HTTP/1.1" 406 -

I added a new line in the exception catching code to print the only path referenced in the code in this code block (app.config['LOCAL_STORAGE_FOLDER']) which in this case resolves to /home/dstone/sketchy/files 
There are no symbolic links that are a part of or within this path.

Any help would be much appreciated.

**Comment by sbehrens** [comment]
How many files are in /home/dstone/sketchy/files?

**Comment by sbehrens** [comment]
Please let me know if your issue is resolved.

**Comment by sbehrens** [comment]
Closed due to no reply from reporter.
