### ISSUE TITLE
Clean install on MacOS, needs also a MySQL Installation

### ISSUE THREAD

**Issue by idev** [Netflix/sketchy#17]
Hello,

I installed sketchy by following the manual steps on the manual. But it skipped on step "python setup.py install" with the error EnvironmentError: mysql_config not found.

After installing mysql with brew install mysql, everything works fine!

Thanks for your great work.

**Comment by sbehrens** [comment]
Sketchy prod uses mysql as the recommended database engine.  I'll add some guidance in the documentation on that dependency.

**Comment by sbehrens** [comment]
Wiki updated.
