### ISSUE TITLE
Sketchy is not creating screenshots for scrumblr

### ISSUE THREAD

**Issue by idev** [Netflix/sketchy#18]
Hello,

I get scrumblr up and running, and try to make it work also with sketchy.
I installed sketchy and also get it to work with a test capture, like documented in the wiki.

But it seems not to work with scrumblr, I only see that the jobs are created and if I list them with http://localhost:8000/api/v1.0/capture I get a list of them. But all jobs from scrumblr have null values:

> "callback": "http://localhost:3000/results/55/update_screenshot", 
 "capture_status": null, 
        "created_at": "2015-05-12 10:52:56.470125", 
        "html_url": null, 
        "id": 3, 
        "job_status": "CREATED", 
        "modified_at": "None", 
        "retry": null, 
        "scrape_url": null, 
        "sketch_url": null, 
        "url": "https://www.reddit.com/r/netflix/comments/10w39c/top_5_on_netflix_instant/", 
        "url_response_code": null

Test capture worked:
> "capture_status": "LOCAL_CAPTURES_CREATED", 
        "created_at": "2015-05-12 10:41:31.031672", 
        "html_url": "http://127.0.0.1:8000/files/google.com_1.html", 
        "id": 1, 
        "job_status": "COMPLETED", 
        "modified_at": "2015-05-12 10:41:38.840162", 
        "retry": null, 
        "scrape_url": "http://127.0.0.1:8000/files/google.com_1.txt", 
        "sketch_url": "http://127.0.0.1:8000/files/google.com_1.png", 
        "url": "http://google.com", 
        "url_response_code": 200

Any suggestions?

Thanks!

**Comment by idev** [comment]
Can be closed, celery was not running correctly.

**Comment by sbehrens** [comment]
Thanks.
