### ISSUE TITLE
sqlalchemy.exc.OperationalError

### ISSUE THREAD

**Issue by kolulu** [Netflix/sketchy#27]
hi everyone,
when I try to create a capture in a test mode using I get "sqlalchemy.exc.OperationalError", for production setup it is "404 Not Found  nginx/1.4.6 (Ubuntu)".
I installed Sketchy on Ubuntu 14.04 using scripted install and I use 3 terminals to run it as @sbehrens mentioned in #15 . 
I have no idea how to deal with it, I would be grateful if you'd help me to configure Sketchy with Scumblr. Thanks is advance

**Comment by sbehrens** [comment]
Can you send me your nginx configuration file?  
In addition, can you send me your nginx.log file?

**Comment by sbehrens** [comment]
Hi @kolulu, I am closing this issue please reopen with nginx.log and nginx configuration file if you are still having issues.
