### ISSUE TITLE
Lack of PostgreSQL connector

### ISSUE THREAD

**Issue by fenicks** [Netflix/sketchy#30]
The setup.py doesn't mention PostgreSQL's connector.
I have an error when launching sketchy in docker container : 
`ImportError: No module named psycopg2`

**Comment by sbehrens** [comment]
@fenicks I haven't setup Postgres for Sketchy.  IT should support MySQL and the associated connectors without requiring any configuration changes.  Since it uses SQLAlchemy under the hood, if you would like to use Postgres you could add `psycopg2` to the setup.py file.

**Comment by fenicks** [comment]
@sbehrens When adding `psycopg2` in setup.py everything is OK, thank you.
