### ISSUE TITLE
Unable to capture screenshot

### ISSUE THREAD

**Issue by weichea** [Netflix/sketchy#34]
Received the error when using the test start up. It works the first time, and broke after a reboot. 

sqlalchemy.exc.OperationalError

OperationalError: (OperationalError) no such table: Capture u'INSERT INTO "Capture" (url, job_status, capture_status, created_at, modified_at, sketch_url, scrape_url, html_url, status_only, callback, retry, url_response_code) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' ('http://google.com', 'CREATED', None, '2016-05-27 15:02:38.862897', None, None, None, None, None, None, None, None)

**Comment by enasda** [comment]
I have the same problem too

**Comment by sbehrens** [comment]
That typically menas the DB isn't created:

```
python manage.py create_db
```

Should do the trick.  Can you please try that and report back?  Also, what method did you use for setup?

**Comment by sbehrens** [comment]
https://github.com/Netflix/sketchy/commit/d601c100b5257f98da5dcfe448dd8b1eea3062d5 fixes this issue (moving out of /tmp to base_dir)

**Comment by enasda** [comment]
yes thank I tried it and it worked.

**Comment by enasda** [comment]
@sbehrens  thanks for your help but I noticed that Scumblr stopped receiving screenshots when I moved SQLite db from /tmp to base_dir  as the status of the screenshot remain "requested" noting that it was created in sketchy as bellow 
  {
        "callback": "http://localhost:3000/results/101/update_screenshot", 
        "capture_status": "LOCAL_CAPTURES_CREATED", 
        "created_at": "2016-06-23 13:43:58.233854", 
        "html_url": "http://192.168.236.128:8000/files/www.******.com_3.html", 
        "id": 3, 
        "job_status": "COMPLETED", 
        "modified_at": "2016-06-23 13:44:10.744406", 
        "retry": 0, 
        "scrape_url": "http://192.168.236.128:8000/files/www.******.com_3.txt", 
        "sketch_url": "http://192.168.236.128:8000/files/www.*****.com_3.png", 
        "url": "http://www..******.com/etraining.php", 
        "url_response_code": 200

**Comment by sbehrens** [comment]
It's stated that it created the local captures, however you are stating that it didn't complete the callback to Scumblr?  

If you try to visit the `html_url`, can you download the file?

**Comment by sbehrens** [comment]
@ahoernecke Looping you on in Scumblr side.

**Comment by enasda** [comment]
yes I can download it by visiting the html_url  and now I am facing a new problem when I try to attach a screenshot as I got the following error I don't know what I did wrong because it was working fine, I added a new user using `rails c` I don't know if that could be related to the problem. 

![image](https://cloud.githubusercontent.com/assets/20086864/16399184/e039ffac-3cd8-11e6-90e8-4cacf34c7ca8.png)

**Comment by ahoernecke** [comment]
Hey @ensada,

Can you ensure the account that is running the rails app has permission to write to the public folder (and subfolders)?

**Comment by enasda** [comment]
yes it has

**Comment by sbehrens** [comment]
More specifically can you tell us the users running scumblr and sketchy?

```
ps aux | grep scumblr && ps aux | grep sketchy
```

And then can you do the following in `/home/test/Scumblr/public`

```
find . -ls | awk '{print $3,$5,$6,$11}' | grep "^d" | awk '{print $2,$3,$4}' | sort -u
```
That will help us see if it's an ownership issue.

**Comment by enasda** [comment]
> ps aux | grep scumblr && ps aux | grep sketchy

> root       2416  0.0  0.0   9416   936 pts/0    S+   17:59   0:00 grep --color=auto scumblr
> test       2261  0.4  1.4 133680 49228 ?        S    17:56   0:01 /usr/bin/python /usr/local/bin/celery worker -A sketchy.celery
> test       2263  0.0  0.4  54028 15428 ?        S    17:56   0:00 /usr/bin/python /usr/local/bin/gunicorn sketchy:app -b 0.0.0.0:8000
> test       2274  0.2  1.3 133028 46548 ?        S    17:56   0:00 /usr/bin/python /usr/local/bin/gunicorn sketchy:app -b 0.0.0.0:8000
> test       2277  0.0  1.2 129900 43860 ?        S    17:56   0:00 /usr/bin/python /usr/local/bin/celery worker -A sketchy.celery
> root       2418  0.0  0.0   9416   936 pts/0    S+   17:59   0:00 grep --color=auto sketchy


> find . -ls | awk '{print $3,$5,$6,$11}' | grep "^d" | awk '{print $2,$3,$4}' | sort -u
> 
> 
> root root ./system
> root root ./system/result_attachments
> root root ./system/result_attachments/attachments
> root root ./system/result_attachments/attachments/000
> root root ./system/result_attachments/attachments/000/000
> root root ./system/result_attachments/attachments/000/000/001
> root root ./system/result_attachments/attachments/000/000/001/medium
> root root ./system/result_attachments/attachments/000/000/001/original
> root root ./system/result_attachments/attachments/000/000/001/thumb
> root root ./system/result_attachments/attachments/000/000/002
> root root ./system/result_attachments/attachments/000/000/002/medium
> root root ./system/result_attachments/attachments/000/000/002/original
> root root ./system/result_attachments/attachments/000/000/002/thumb
> root root ./system/result_attachments/attachments/000/000/003
> root root ./system/result_attachments/attachments/000/000/003/medium
> root root ./system/result_attachments/attachments/000/000/003/original
> root root ./system/result_attachments/attachments/000/000/003/thumb
> root root ./system/result_attachments/attachments/000/000/004
> root root ./system/result_attachments/attachments/000/000/004/medium
> root root ./system/result_attachments/attachments/000/000/004/original
> root root ./system/result_attachments/attachments/000/000/004/thumb
> root root ./system/result_attachments/attachments/000/000/005
> root root ./system/result_attachments/attachments/000/000/005/medium
> root root ./system/result_attachments/attachments/000/000/005/original
> root root ./system/result_attachments/attachments/000/000/005/thumb
> root root ./system/result_attachments/attachments/000/000/006
> root root ./system/result_attachments/attachments/000/000/006/medium
> root root ./system/result_attachments/attachments/000/000/006/original
> root root ./system/result_attachments/attachments/000/000/006/thumb
> root root ./system/result_attachments/attachments/000/000/007
> root root ./system/result_attachments/attachments/000/000/007/medium
> root root ./system/result_attachments/attachments/000/000/007/original
> root root ./system/result_attachments/attachments/000/000/007/thumb
> root root ./system/result_attachments/attachments/000/000/008
> root root ./system/result_attachments/attachments/000/000/008/medium
> root root ./system/result_attachments/attachments/000/000/008/original
> root root ./system/result_attachments/attachments/000/000/008/thumb
> root root ./system/result_attachments/attachments/000/000/009
> root root ./system/result_attachments/attachments/000/000/009/medium
> root root ./system/result_attachments/attachments/000/000/009/original
> root root ./system/result_attachments/attachments/000/000/009/thumb
> root root ./system/result_attachments/attachments/000/000/010
> root root ./system/result_attachments/attachments/000/000/010/medium
> root root ./system/result_attachments/attachments/000/000/010/original
> root root ./system/result_attachments/attachments/000/000/010/thumb
> root root ./system/result_attachments/attachments/000/000/011
> root root ./system/result_attachments/attachments/000/000/011/medium
> root root ./system/result_attachments/attachments/000/000/011/original
> root root ./system/result_attachments/attachments/000/000/011/thumb
> root root ./system/result_attachments/attachments/000/000/012
> root root ./system/result_attachments/attachments/000/000/012/medium
> root root ./system/result_attachments/attachments/000/000/012/original
> root root ./system/result_attachments/attachments/000/000/012/thumb
> root root ./system/result_attachments/attachments/000/000/013
> root root ./system/result_attachments/attachments/000/000/013/medium
> root root ./system/result_attachments/attachments/000/000/013/original
> root root ./system/result_attachments/attachments/000/000/013/thumb
> root root ./system/result_attachments/attachments/000/000/014
> root root ./system/result_attachments/attachments/000/000/014/medium
> root root ./system/result_attachments/attachments/000/000/014/original
> root root ./system/result_attachments/attachments/000/000/014/thumb
> root root ./system/result_attachments/attachments/000/000/015
> root root ./system/result_attachments/attachments/000/000/015/medium
> root root ./system/result_attachments/attachments/000/000/015/original
> root root ./system/result_attachments/attachments/000/000/015/thumb
> root root ./system/result_attachments/attachments/000/000/016
> root root ./system/result_attachments/attachments/000/000/016/medium
> root root ./system/result_attachments/attachments/000/000/016/original
> root root ./system/result_attachments/attachments/000/000/016/thumb
> root root ./system/result_attachments/attachments/000/000/017
> root root ./system/result_attachments/attachments/000/000/017/medium
> root root ./system/result_attachments/attachments/000/000/017/original
> root root ./system/result_attachments/attachments/000/000/017/thumb
> root root ./system/result_attachments/attachments/000/000/018
> root root ./system/result_attachments/attachments/000/000/018/medium
> root root ./system/result_attachments/attachments/000/000/018/original
> root root ./system/result_attachments/attachments/000/000/018/thumb
> root root ./system/result_attachments/attachments/000/000/019
> root root ./system/result_attachments/attachments/000/000/019/medium
> root root ./system/result_attachments/attachments/000/000/019/original
> root root ./system/result_attachments/attachments/000/000/019/thumb
> root root ./system/result_attachments/attachments/000/000/020
> root root ./system/result_attachments/attachments/000/000/020/medium
> root root ./system/result_attachments/attachments/000/000/020/original
> root root ./system/result_attachments/attachments/000/000/020/thumb
> root root ./system/result_attachments/attachments/000/000/021
> root root ./system/result_attachments/attachments/000/000/021/medium
> root root ./system/result_attachments/attachments/000/000/021/original
> root root ./system/result_attachments/attachments/000/000/021/thumb
> root root ./system/result_attachments/attachments/000/000/022
> root root ./system/result_attachments/attachments/000/000/022/medium
> root root ./system/result_attachments/attachments/000/000/022/original
> root root ./system/result_attachments/attachments/000/000/022/thumb
> root root ./system/result_attachments/attachments/000/000/023
> root root ./system/result_attachments/attachments/000/000/023/medium
> root root ./system/result_attachments/attachments/000/000/023/original
> root root ./system/result_attachments/attachments/000/000/023/thumb
> root root ./system/result_attachments/attachments/000/000/024
> root root ./system/result_attachments/attachments/000/000/024/medium
> root root ./system/result_attachments/attachments/000/000/024/original
> root root ./system/result_attachments/attachments/000/000/024/thumb
> root root ./system/result_attachments/attachments/000/000/025
> root root ./system/result_attachments/attachments/000/000/025/medium
> root root ./system/result_attachments/attachments/000/000/025/original
> root root ./system/result_attachments/attachments/000/000/025/thumb
> root root ./system/result_attachments/attachments/000/000/026
> root root ./system/result_attachments/attachments/000/000/026/medium
> root root ./system/result_attachments/attachments/000/000/026/original
> root root ./system/result_attachments/attachments/000/000/026/thumb
> root root ./system/result_attachments/attachments/000/000/027
> root root ./system/result_attachments/attachments/000/000/027/medium
> root root ./system/result_attachments/attachments/000/000/027/original
> root root ./system/result_attachments/attachments/000/000/027/thumb
> root root ./system/result_attachments/attachments/000/000/028
> root root ./system/result_attachments/attachments/000/000/028/medium
> root root ./system/result_attachments/attachments/000/000/028/original
> root root ./system/result_attachments/attachments/000/000/028/thumb
> root root ./system/result_attachments/attachments/000/000/029
> root root ./system/result_attachments/attachments/000/000/029/medium
> root root ./system/result_attachments/attachments/000/000/029/original
> root root ./system/result_attachments/attachments/000/000/029/thumb
> root root ./system/result_attachments/attachments/000/000/030
> root root ./system/result_attachments/attachments/000/000/030/medium
> root root ./system/result_attachments/attachments/000/000/030/original
> root root ./system/result_attachments/attachments/000/000/030/thumb
> root root ./system/result_attachments/attachments/000/000/031
> root root ./system/result_attachments/attachments/000/000/031/medium
> root root ./system/result_attachments/attachments/000/000/031/original
> root root ./system/result_attachments/attachments/000/000/031/thumb
> root root ./system/result_attachments/attachments/000/000/032
> root root ./system/result_attachments/attachments/000/000/032/medium
> root root ./system/result_attachments/attachments/000/000/032/original
> root root ./system/result_attachments/attachments/000/000/032/thumb
> root root ./system/result_attachments/attachments/000/000/033
> root root ./system/result_attachments/attachments/000/000/033/medium
> root root ./system/result_attachments/attachments/000/000/033/original
> root root ./system/result_attachments/attachments/000/000/033/thumb
> root root ./system/result_attachments/attachments/000/000/034
> root root ./system/result_attachments/attachments/000/000/034/medium
> root root ./system/result_attachments/attachments/000/000/034/original
> root root ./system/result_attachments/attachments/000/000/034/thumb
> root root ./system/result_attachments/attachments/000/000/035
> root root ./system/result_attachments/attachments/000/000/035/medium
> root root ./system/result_attachments/attachments/000/000/035/original
> root root ./system/result_attachments/attachments/000/000/035/thumb
> root root ./system/result_attachments/attachments/000/000/036
> root root ./system/result_attachments/attachments/000/000/036/medium
> root root ./system/result_attachments/attachments/000/000/036/original
> root root ./system/result_attachments/attachments/000/000/036/thumb
> root root ./system/result_attachments/attachments/000/000/037
> root root ./system/result_attachments/attachments/000/000/037/medium
> root root ./system/result_attachments/attachments/000/000/037/original
> root root ./system/result_attachments/attachments/000/000/037/thumb
> root root ./system/result_attachments/attachments/000/000/038
> root root ./system/result_attachments/attachments/000/000/038/medium
> root root ./system/result_attachments/attachments/000/000/038/original
> root root ./system/result_attachments/attachments/000/000/038/thumb
> root root ./system/result_attachments/attachments/000/000/039
> root root ./system/result_attachments/attachments/000/000/039/medium
> root root ./system/result_attachments/attachments/000/000/039/original
> root root ./system/result_attachments/attachments/000/000/039/thumb
> root root ./system/result_attachments/attachments/000/000/040
> root root ./system/result_attachments/attachments/000/000/040/medium
> root root ./system/result_attachments/attachments/000/000/040/original
> root root ./system/result_attachments/attachments/000/000/040/thumb
> root root ./system/result_attachments/attachments/000/000/041
> root root ./system/result_attachments/attachments/000/000/041/medium
> root root ./system/result_attachments/attachments/000/000/041/original
> root root ./system/result_attachments/attachments/000/000/041/thumb
> root root ./system/result_attachments/attachments/000/000/042
> root root ./system/result_attachments/attachments/000/000/042/medium
> root root ./system/result_attachments/attachments/000/000/042/original
> root root ./system/result_attachments/attachments/000/000/042/thumb
> root root ./system/result_attachments/attachments/000/000/043
> root root ./system/result_attachments/attachments/000/000/043/medium
> root root ./system/result_attachments/attachments/000/000/043/original
> root root ./system/result_attachments/attachments/000/000/043/thumb
> test test
>

**Comment by sbehrens** [comment]
Thanks we are getting close, one more command, if you could!

```
ps aux | grep rails
```

**Comment by enasda** [comment]
root       2329  0.7  3.9 955524 137352 pts/0   Sl   17:57   0:05 rails master                          
root       2367  3.4  4.5 988696 158840 pts/0   Sl   17:57   0:25 rails worker[0]                       
root       2548  0.0  0.0   9416   944 pts/0    S+   18:09   0:00 grep --color=auto rails

**Comment by sbehrens** [comment]
@ahoernecke The folder permissions look okay since rails is running as root.  any thoughts?

**Comment by enasda** [comment]
I changed the sqlite db  to the /tmp and then moved it back to base_dir , I don't know what was the problem but it is working now.

**Comment by enasda** [comment]
when I restarted sketchy the same issue happened again  I think the problem has something to do with db.

**Comment by sbehrens** [comment]
Hi Ensada,

Was this the issue with Sketchy or with Scumblr error?

**Comment by enasda** [comment]
when I try 

> http://:8000/eager?url&type=sketch  
it download the screenshot but when I generate it using Scumblr  It doesn't return the screenshot, and when I try to attach a screenshot I get the error in the snapshot above "permission denied" so I don't know where is the issue exactly? 
I restarted both Scumblr and sketchy when the problem happened again.

**Comment by sbehrens** [comment]
It sounds like it still may be a file permission related issue.  Just to
confirm, you can generate a screenshot using the API in sketchy and
download the sketchy manually outside of Scumblr?

**Comment by enasda** [comment]
yes I can

**Comment by sbehrens** [comment]
Just as a temporary check, try changing the public folder to 777 and see if that resolves the issue.  If so, it's a file permission issue.  

```
cd /home/test/Scumblr/public
sudo chmod -R 777 .
```

You will want to change this back as you are giving rw access to all users on your system.

**Comment by enasda** [comment]
yes it worked

**Comment by sbehrens** [comment]
That's the issue, it seems to be related to your file permissions.  I would suggest trying to ensure Scumblr can write the files to the public directories where you first saw the Scumblr error.
