### ISSUE TITLE
Only screenshot/scrap content if page has changed?

### ISSUE THREAD

**Issue by roxy9990** [Netflix/sketchy#38]
Is it possible to configure sketchy to only screenshot/scrape content from a website if the website has changed? Is it possible to setup alerting for when a site changes or provide history for the website changes? Seems like a great tool. Thanks

**Comment by sbehrens** [comment]
Hi @roxy9990,
Sketchy has no concept of state, it simply calls PhantomJS to screenshot and scrape any page fed to the API.  IF you wanted to introduce that logic, you would need to do that in the application you are using Sektchy with.  

If you are using Scumblr with Sketchy, Scumblr would be the right place to introduce this logic.  There are some ways to limit screenshoting with Scumblr, so if that is what you are using please let me know.
