### ISSUE TITLE
Sketchy Returning ERROR Server 500 when successful

### ISSUE THREAD

**Issue by x00x70** [Netflix/sketchy#41]
So i have successfully configured Sketchy with S3 on my server and all is working for captures.
However, within my callbacks, and sketchy task status, it is returning error messages, even though the captures are successful and available on S3.

In my Callback JSON:
`"capture_status": "500 Server Error: INTERNAL SERVER ERROR",`
`"job_status": "FAILURE",`

Callback json also contains valid links to the sketch, scrape and html on my S3 bucket.

in my sketchy.log:
`2017-07-23 23:06:30,998 ERROR: 500 Server Error: INTERNAL SERVER ERROR [in /var/sketchy/sketchy/controllers/tasks.py:383]`

Looking at `sketchy/controllers/tasks.py` i can see the code that is raising this Error, however, as all the S3 uploading is successful, i have no idea why an exception is being raised?  Please can you advise where to look next?

I really need to get the correct job_statuses out of the callback json if possible.

**Comment by sbehrens** [comment]
Hi @x00x70 ,

Where are you having Sketchy callback to?  Is it Scumblr or something else?

**Comment by x00x70** [comment]
It was a problem with my system receiving the callback, which i fixed - thanks for quick response. 

Interesting that if the callback location doesnt return a 200, Sketchy throws this error. Any idea why?

**Comment by sbehrens** [comment]
Good to hear!

A 200 would be the expected Status code.  I would also think 201 would be allowed.  3xx, 4xx, 5xx would result in an error since those would either indicate the URL isn't at the right location and needs to redirect (3xx), the file isn't there or is forbidden (4xx), or the application has an error (5xx).  Do you happen to know what code it was returning?

**Comment by x00x70** [comment]
yeah my callback server was returning a 500. Does sketchy make two callbacks? was it getting the 500 error from the first callback, and then erroring on the second? All sorted now, but this was a pain to debug, as i was getting all the data passed through, i just hadn't set my callback up to give a proper response...
